import { Destination } from "./types";

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: "DEST-2026-01",
    name: "Melbourne Eastern Quarry Terminal",
    jobId: "JOB-2026-01",
    jobRef: "PO-2026-01",
    customerId: "C-401",
    customerName: "Apex Infrastructure Group",
    phone: "+61 3 9845 2200",
    status: "Active",
    addressLine1: "102 Quarry Rd",
    addressLine2: "Lilydale Gate A",
    suburb: "Lilydale",
    state: "VIC",
    postcode: "3140",
    notes: "Direct heavy vehicle entrance. Driver site induction required before weighbridge crossing."
  },
  {
    id: "DEST-2026-02",
    name: "Monash Freeway Upgrade Site B",
    jobId: "JOB-2026-01",
    jobRef: "PO-2026-01",
    customerId: "C-401",
    customerName: "Apex Infrastructure Group",
    phone: "+61 412 345 611",
    status: "Active",
    addressLine1: "Exit 18, M1 Highway",
    addressLine2: "",
    suburb: "Glen Waverley",
    state: "VIC",
    postcode: "3150",
    notes: "Night shifts only. Call dispatch 30 mins prior to arrival on site."
  },
  {
    id: "DEST-2026-03",
    name: "Dandenong South Industrial Depot",
    jobId: "JOB-2026-02",
    jobRef: "PO-2026-02",
    customerId: "C-402",
    customerName: "Bayside Civil Construction",
    phone: "+61 3 9522 9900",
    status: "Active",
    addressLine1: "88 Industry Blvd",
    addressLine2: "",
    suburb: "Dandenong South",
    state: "VIC",
    postcode: "3175",
    notes: "Aggregates stockpile gate 4. Unloading hours 07:00 to 16:30 weekdays."
  },
  {
    id: "DEST-2026-04",
    name: "Altona Concrete Blending Complex",
    jobId: "JOB-2026-C3",
    jobRef: "PO-2026-PINN",
    customerId: "C-403",
    customerName: "Pinnacle Concrete Solutions",
    phone: "+61 411 988 500",
    status: "Active",
    addressLine1: "Altona Road Gate A",
    addressLine2: "Altona Depot",
    suburb: "Altona",
    state: "VIC",
    postcode: "3018",
    notes: "High volume transit lane. Strict speed limits of 10km/h enforced across plant."
  },
  {
    id: "DEST-2026-05",
    name: "Western Ring Road Interchange",
    jobId: "JOB-2026-04",
    jobRef: "PO-2026-APEX4",
    customerId: "C-401",
    customerName: "Apex Infrastructure Group",
    phone: "+61 3 9845 2200",
    status: "Active",
    addressLine1: "Furlong Rd",
    addressLine2: "Sunshine Depot",
    suburb: "Sunshine",
    state: "VIC",
    postcode: "3020",
    notes: "Access permitted for quad-dogs and semi-trailers only."
  },
  {
    id: "DEST-2026-06",
    name: "Yarra Botanical Gardens Expansion",
    jobId: "JOB-2026-05",
    jobRef: "PO-2026-ECOY",
    customerId: "C-405",
    customerName: "Yarra Eco-landscaping",
    phone: "+61 422 931 004",
    status: "Active",
    addressLine1: "322 Melba Hwy",
    addressLine2: "",
    suburb: "Yarra Glen",
    state: "VIC",
    postcode: "3775",
    notes: "Soil and aggregates sorting platform. Gate 1 next to the nursery."
  },
  {
    id: "DEST-2026-07",
    name: "Gippsland Water Supply Gate 2",
    jobId: "JOB-2026-06",
    jobRef: "PO-2026-GIPP",
    customerId: "C-406",
    customerName: "Gippsland Earth Group",
    phone: "+61 422 121 009",
    status: "Inactive",
    addressLine1: "Latrobe Rd",
    addressLine2: "",
    suburb: "Morwell",
    state: "VIC",
    postcode: "3840",
    notes: "Currently suspended due to customer account lockout."
  }
];
