import { Transaction, Product, Customer, Carrier, Driver, Vehicle, TransactionStatus, AdminUser, DocketConfig } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "P-123",
    name: "Crushed Rock 20mm",
    category: "Aggregates",
    subcategory: "Base Materials",
    basePrice: 24.50,
    unit: "Tonne",
    vendor: "V001 - Melbourne Quarry Corp",
    warrantyDays: 1080,
    status: "Active",
    description: "Premium crushed basalt aggregate certified for road base base course and mechanical stabilization.",
    createdDate: "2024-03-10 14:22 PM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 24.50, minQuantity: 0 },
      { tier: "Tier 2", pricePerTonne: 22.80, minQuantity: 500 },
      { tier: "Tier 3", pricePerTonne: 21.00, minQuantity: 1000 }
    ],
    recentLots: [
      { lotNumber: "PL-123-001", orderQuantity: 1200, availableQuantity: 340, status: "Active" },
      { lotNumber: "PL-123-002", orderQuantity: 800, availableQuantity: 0, status: "Completed" }
    ]
  },
  {
    id: "P-124",
    name: "Crusher Dust",
    category: "Aggregates",
    subcategory: "Crushed Material",
    basePrice: 18.75,
    unit: "Tonne",
    vendor: "V002 - BuildRock Supplies",
    warrantyDays: 0,
    status: "Active",
    description: "High quality crusher dust suitable for compacting, paving underlays, and concrete works.",
    createdDate: "2024-03-14 09:15 AM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 18.75, minQuantity: 0 },
      { tier: "Tier 2", pricePerTonne: 17.50, minQuantity: 500 },
      { tier: "Tier 3", pricePerTonne: 16.25, minQuantity: 1000 }
    ],
    recentLots: [
      { lotNumber: "PL-124-001", orderQuantity: 1000, availableQuantity: 450, status: "Active" },
      { lotNumber: "PL-124-002", orderQuantity: 800, availableQuantity: 0, status: "Completed" },
      { lotNumber: "PL-124-003", orderQuantity: 1200, availableQuantity: 850, status: "Active" }
    ]
  },
  {
    id: "P-125",
    name: "Road Base 40mm",
    category: "Aggregates",
    subcategory: "Base Materials",
    basePrice: 22.00,
    unit: "Tonne",
    vendor: "V001 - Melbourne Quarry Corp",
    warrantyDays: 1080,
    status: "Active",
    description: "Finer grade sub-base for general civil works and heavy duty gravel roads.",
    createdDate: "2024-03-11 11:40 AM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 22.00, minQuantity: 0 },
      { tier: "Tier 2", pricePerTonne: 20.50, minQuantity: 500 }
    ],
    recentLots: [
      { lotNumber: "PL-125-001", orderQuantity: 2000, availableQuantity: 1100, status: "Active" }
    ]
  },
  {
    id: "P-126",
    name: "Concrete Sand",
    category: "Sand",
    subcategory: "Fine Aggregate",
    basePrice: 16.00,
    unit: "Tonne",
    vendor: "V003 - Delta Sand Mines",
    warrantyDays: 0,
    status: "Active",
    description: "Washed concrete sand for high quality structural cement blending.",
    createdDate: "2024-02-28 08:30 AM",
    createdBy: "Supervisor Log",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 16.00, minQuantity: 0 },
      { tier: "Tier 2", pricePerTonne: 15.00, minQuantity: 300 }
    ],
    recentLots: [
      { lotNumber: "PL-126-001", orderQuantity: 1500, availableQuantity: 120, status: "Active" }
    ]
  },
  {
    id: "P-127",
    name: "Riversand",
    category: "Sand",
    subcategory: "Natural Sand",
    basePrice: 17.25,
    unit: "Tonne",
    vendor: "V003 - Delta Sand Mines",
    warrantyDays: 0,
    status: "Active",
    description: "Coarse river sand ideal for turf dressing, brick laying, and plastering projects.",
    createdDate: "2023-11-20 16:15 PM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 17.25, minQuantity: 0 }
    ],
    recentLots: [
      { lotNumber: "PL-127-001", orderQuantity: 500, availableQuantity: 0, status: "Completed" }
    ]
  },
  {
    id: "P-128",
    name: "Washed Sand",
    category: "Sand",
    subcategory: "Washed Minerals",
    basePrice: 19.50,
    unit: "Tonne",
    vendor: "V003 - Delta Sand Mines",
    warrantyDays: 0,
    status: "Active",
    description: "Double washed triple filtered fine sand for specialized industrial applications.",
    createdDate: "2023-11-21 10:00 AM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 19.50, minQuantity: 0 }
    ],
    recentLots: []
  },
  {
    id: "P-129",
    name: "Granite 10mm",
    category: "Aggregates",
    subcategory: "Decorative",
    basePrice: 26.00,
    unit: "Tonne",
    vendor: "V001 - Melbourne Quarry Corp",
    warrantyDays: 1080,
    status: "Active",
    description: "Durable granite screenings for pathways driveways and decorative garden features.",
    createdDate: "2024-01-15 15:00 PM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 26.00, minQuantity: 0 }
    ],
    recentLots: [
      { lotNumber: "PL-129-001", orderQuantity: 600, availableQuantity: 240, status: "Active" }
    ]
  },
  {
    id: "P-130",
    name: "Granite 20mm",
    category: "Aggregates",
    subcategory: "Structural",
    basePrice: 26.50,
    unit: "Tonne",
    vendor: "V001 - Melbourne Quarry Corp",
    warrantyDays: 1080,
    status: "Active",
    description: "Angular coarse granite gravel suitable for high strength concrete mixes.",
    createdDate: "2024-01-15 15:10 PM",
    createdBy: "Admin User",
    pricingTiers: [],
    recentLots: []
  },
  {
    id: "P-136",
    name: "Recycled Concrete",
    category: "Recycled",
    subcategory: "Eco-aggregate",
    basePrice: 15.50,
    unit: "Tonne",
    vendor: "V005 - GreenCycle Eco Group",
    warrantyDays: 0,
    status: "Active",
    description: "Crushed recycled concrete demolition scrap processed and graded to 20mm dry.",
    createdDate: "2024-02-10 11:20 AM",
    createdBy: "Admin User",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 15.50, minQuantity: 0 },
      { tier: "Tier 2", pricePerTonne: 14.00, minQuantity: 600 }
    ],
    recentLots: [
      { lotNumber: "PL-136-101", orderQuantity: 1800, availableQuantity: 1400, status: "Active" }
    ]
  },
  {
    id: "P-137",
    name: "Top Soil",
    category: "Soil",
    subcategory: "Organic Soil",
    basePrice: 14.00,
    unit: "Tonne",
    vendor: "V006 - Southern Earthworks",
    warrantyDays: 0,
    status: "Active",
    description: "Screened organic garden top soil rich with compost and essential trace plant nutrients.",
    createdDate: "2024-03-01 13:00 PM",
    createdBy: "Supervisor Log",
    pricingTiers: [
      { tier: "Tier 1", pricePerTonne: 14.00, minQuantity: 0 }
    ],
    recentLots: [
      { lotNumber: "PL-137-01", orderQuantity: 500, availableQuantity: 150, status: "Active" }
    ]
  },
  {
    id: "P-138",
    name: "Fill Material",
    category: "Soil",
    subcategory: "Subsoil fill",
    basePrice: 12.50,
    unit: "Tonne",
    vendor: "V006 - Southern Earthworks",
    warrantyDays: 0,
    status: "Active",
    description: "Unscreened clean fill dirt for structural cavity fillings and site leveling.",
    createdDate: "2024-03-01 13:15 PM",
    createdBy: "Supervisor Log",
    pricingTiers: [],
    recentLots: []
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "C-401",
    name: "Apex Infrastructure Group",
    contactPerson: "Jonathan Vance",
    email: "j.vance@apexinfra.com",
    phone: "+61 3 9845 2210",
    status: "Active",
    billingAddress: "Level 14, 530 Collins St, Melbourne VIC 3000",
    paymentTerms: "30 Days Net",
    creditLimit: 250000,
    activeContracts: 4,
    recentActivityDate: "2026-06-22",
    customerCode: "APEXINFRA",
    mobileNo: "+61 412 345 601",
    fax: "+61 3 9845 2211",
    addressLine1: "Level 14, 530 Collins St",
    addressLine2: "Main Office Tower",
    suburbName: "Melbourne",
    stateCode: "VIC",
    postCodeVal: "3000",
    pricingTier: "Tier 2 - Volume Pricing",
    accountBalance: 14250.00,
    lastTransactionDate: "2026-06-22",
    createdOn: "2024-01-15",
    createdBy: "System Admin",
    modifiedOn: "2026-06-20",
    modifiedBy: "Admin User",
    notes: "Preferred primary contractor. High volume aggregates and roadbase receiver.",
    clientSince: "2024"
  },
  {
    id: "C-402",
    name: "Bayside Civil Construction",
    contactPerson: "Sarah Jenkins",
    email: "billing@baysidecivil.com.au",
    phone: "+61 3 9522 9911",
    status: "Active",
    billingAddress: "45 Industrial Ave, Dandenong VIC 3175",
    paymentTerms: "14 Days Net",
    creditLimit: 120000,
    activeContracts: 2,
    recentActivityDate: "2026-06-21",
    customerCode: "BAYSIDECIV",
    mobileNo: "+61 412 345 602",
    fax: "+61 3 9522 9912",
    addressLine1: "45 Industrial Ave",
    addressLine2: "Depot B",
    suburbName: "Dandenong",
    stateCode: "VIC",
    postCodeVal: "3175",
    pricingTier: "Tier 1 - Standard Rate",
    accountBalance: 4850.25,
    lastTransactionDate: "2026-06-21",
    createdOn: "2024-03-12",
    createdBy: "Operator #03",
    modifiedOn: "2026-06-18",
    modifiedBy: "Admin User",
    notes: "Local civil contractor. Frequently purchases crusher dust and concrete sand.",
    clientSince: "2024"
  },
  {
    id: "C-403",
    name: "Pinnacle Concrete Solutions",
    contactPerson: "Robert Thorne",
    email: "thorner@pinconcrete.com",
    phone: "+61 411 988 543",
    status: "Active",
    billingAddress: "Building 3B, 80 Toll Drive, Altona VIC 3018",
    paymentTerms: "Immediate",
    creditLimit: 50000,
    activeContracts: 1,
    recentActivityDate: "2026-06-22",
    customerCode: "PINNACLECON",
    mobileNo: "+61 411 988 543",
    fax: "+61 3 9933 0041",
    addressLine1: "Building 3B",
    addressLine2: "80 Toll Drive",
    suburbName: "Altona",
    stateCode: "VIC",
    postCodeVal: "3018",
    pricingTier: "Tier 3 - Concrete Aggregate Special",
    accountBalance: 0.00,
    lastTransactionDate: "2026-06-22",
    createdOn: "2024-05-18",
    createdBy: "System Admin",
    modifiedOn: "2026-06-21",
    modifiedBy: "Admin User",
    notes: "Cash account. Pre-authorized and cleared on outbound weigh-out.",
    clientSince: "2024"
  },
  {
    id: "C-404",
    name: "Metro Roads Joint Venture",
    contactPerson: "David Miller",
    email: "d.miller@mrjv.gov.au",
    phone: "+61 3 8310 4000",
    status: "Active",
    billingAddress: "600 Bourke St, Melbourne VIC 3000",
    paymentTerms: "60 Days Net",
    creditLimit: 800000,
    activeContracts: 9,
    recentActivityDate: "2026-06-22",
    customerCode: "METROROADS",
    mobileNo: "+61 412 345 604",
    fax: "+61 3 8310 4001",
    addressLine1: "600 Bourke St",
    addressLine2: "Floor 22",
    suburbName: "Melbourne",
    stateCode: "VIC",
    postCodeVal: "3000",
    pricingTier: "Tier 4 - Major Infrastructure Rate",
    accountBalance: 85200.00,
    lastTransactionDate: "2026-06-22",
    createdOn: "2023-08-20",
    createdBy: "System Admin",
    modifiedOn: "2026-06-22",
    modifiedBy: "Admin User",
    notes: "Government arterial road project consortium. High credit allowance approved.",
    clientSince: "2023"
  },
  {
    id: "C-405",
    name: "Yarra Eco-landscaping",
    contactPerson: "Nesta Harris",
    email: "nesta@yarraeco.net",
    phone: "+61 402 333 444",
    status: "Active",
    billingAddress: "12 Merri Creek Road, Coburg VIC 3058",
    paymentTerms: "7 Days Net",
    creditLimit: 35000,
    activeContracts: 1,
    recentActivityDate: "2026-06-19",
    customerCode: "YARRAECO",
    mobileNo: "+61 402 333 444",
    fax: "+61 3 9384 1002",
    addressLine1: "12 Merri Creek Road",
    addressLine2: "",
    suburbName: "Coburg",
    stateCode: "VIC",
    postCodeVal: "3058",
    pricingTier: "Tier 1 - Standard Rate",
    accountBalance: 1150.00,
    lastTransactionDate: "2026-06-19",
    createdOn: "2025-02-10",
    createdBy: "Operator #05",
    modifiedOn: "2026-06-19",
    modifiedBy: "Admin User",
    notes: "Specialized landscaping soils and compost mixes. Prompt 7-day payments.",
    clientSince: "2025"
  },
  {
    id: "C-406",
    name: "Gippsland Earth Group",
    contactPerson: "Reginald Vance",
    email: "bills@gippsearth.com.au",
    phone: "+61 3 5132 4492",
    status: "Suspended",
    billingAddress: "Lot 15 Princes Hwy, Morwell VIC 3840",
    paymentTerms: "Immediate Balance",
    creditLimit: 0,
    activeContracts: 0,
    recentActivityDate: "2026-06-10",
    customerCode: "GIPPSEARTH",
    mobileNo: "+61 412 345 606",
    fax: "+61 3 5132 4493",
    addressLine1: "Lot 15 Princes Hwy",
    addressLine2: "",
    suburbName: "Morwell",
    stateCode: "VIC",
    postCodeVal: "3840",
    pricingTier: "Tier 1 - Standard Rate",
    accountBalance: -450.00,
    lastTransactionDate: "2026-06-10",
    createdOn: "2024-11-05",
    createdBy: "System Admin",
    modifiedOn: "2026-06-10",
    modifiedBy: "Admin User",
    notes: "Account suspended due to outstanding long overdue balances and invoice dispute.",
    clientSince: "2024"
  }
];

export const INITIAL_CARRIERS: Carrier[] = [
  { id: "CR-01", name: "Star Bulk Haulage", contactNo: "1300 551 229", email: "ops@starbulk.com.au", status: "Active", vehicleCount: 12 },
  { id: "CR-02", name: "RoadKings Logistics", contactNo: "03 9942 1100", email: "dispatch@roadkings.com.au", status: "Active", vehicleCount: 8 },
  { id: "CR-03", name: "Echo Sand Transport", contactNo: "0499 112 334", email: "transport@echosand.com", status: "Active", vehicleCount: 4 },
  { id: "CR-04", name: "Indie Carters Network", contactNo: "0422 931 004", email: "admin@indiecarters.org", status: "Active", vehicleCount: 15 }
];

export const INITIAL_DRIVERS: Driver[] = [
  { id: "D-001", name: "James Peterson", licenseNumber: "VIC-884920A", carrierId: "CR-01", carrierName: "Star Bulk Haulage", status: "Active", lastWeighedDate: "2026-06-22" },
  { id: "D-002", name: "Mustafa Al-Azawi", licenseNumber: "VIC-902188B", carrierId: "CR-02", carrierName: "RoadKings Logistics", status: "Active", lastWeighedDate: "2026-06-22" },
  { id: "D-003", name: "Bradley Cooper", licenseNumber: "NSW-331049Z", carrierId: "CR-01", carrierName: "Star Bulk Haulage", status: "Active", lastWeighedDate: "2026-06-21" },
  { id: "D-004", name: "Sarah Connor", licenseNumber: "VIC-100293X", carrierId: "CR-03", carrierName: "Echo Sand Transport", status: "Active", lastWeighedDate: "2026-06-22" },
  { id: "D-005", name: "Marcus Fletcher", licenseNumber: "VIC-551229F", carrierId: "CR-04", carrierName: "Indie Carters Network", status: "Active", lastWeighedDate: "2026-06-22" },
  { id: "D-006", name: "Tommy Vercetti", licenseNumber: "QLD-882049H", carrierId: "CR-04", carrierName: "Indie Carters Network", status: "Inactive", lastWeighedDate: "2026-06-15" }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  { plateNumber: "XY-99-ZZ", vehicleType: "Semi-Trailer", carrierName: "Star Bulk Haulage", tareWeight: 14.20, lastTareDate: "2026-06-18", status: "Active" },
  { plateNumber: "WB-40-EE", vehicleType: "Quad-Dog", carrierName: "RoadKings Logistics", tareWeight: 18.50, lastTareDate: "2026-06-20", status: "Active" },
  { plateNumber: "QD-11-AA", vehicleType: "Quad-Dog", carrierName: "Star Bulk Haulage", tareWeight: 19.10, lastTareDate: "2026-06-21", status: "Active" },
  { plateNumber: "ES-04-SS", vehicleType: "6-Wheeler", carrierName: "Echo Sand Transport", tareWeight: 9.80, lastTareDate: "2026-06-12", status: "Active" },
  { plateNumber: "IC-88-TT", vehicleType: "B-Double", carrierName: "Indie Carters Network", tareWeight: 24.60, lastTareDate: "2026-06-15", status: "Active" },
  { plateNumber: "IC-41-YY", vehicleType: "Semi-Trailer", carrierName: "Indie Carters Network", tareWeight: 13.90, lastTareDate: "2026-06-11", status: "Active" }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "TX-40912",
    ticketNo: "WB-991244",
    vehicleReg: "XY-99-ZZ",
    driverName: "James Peterson",
    customerId: "C-401",
    customerName: "Apex Infrastructure Group",
    productId: "P-123",
    productName: "Crushed Rock 20mm",
    carrierName: "Star Bulk Haulage",
    grossWeight: 42.80,
    tareWeight: 14.20,
    netWeight: 28.60,
    firstWeighTime: "2026-06-22 08:31 AM",
    secondWeighTime: "2026-06-22 08:52 AM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.PENDING,
    basePrice: 24.50,
    totalValue: 700.70,
    comments: "Urgent shipment for freeway road foundation. Gross weight verified on Scale B.",
    scaleIdInbound: "Scale-A2",
    scaleIdOutbound: "Scale-B1",
    operatorId: "OP-JohnD",
    auditHistory: [
      { timestamp: "2026-06-22 08:31 AM", action: "First Weigh Inbound", user: "OP-JohnD", details: "Vehicle registered with gross weight 42.80t" },
      { timestamp: "2026-06-22 08:52 AM", action: "Second Weigh Outbound", user: "OP-JohnD", details: "Tare detected at 14.20t. Net calculation 28.60t loaded." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-01",
    lotNo: "LOT-A-42",
    transactionCode: "TR-AC-912",
    accountBalance: 4200.50
  },
  {
    id: "TX-40913",
    ticketNo: "WB-991245",
    vehicleReg: "WB-40-EE",
    driverName: "Mustafa Al-Azawi",
    customerId: "C-402",
    customerName: "Bayside Civil Construction",
    productId: "P-124",
    productName: "Crusher Dust",
    carrierName: "RoadKings Logistics",
    grossWeight: 38.90,
    tareWeight: 18.50,
    netWeight: 20.40,
    firstWeighTime: "2026-06-22 09:05 AM",
    secondWeighTime: "2026-06-22 09:21 AM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.PENDING,
    basePrice: 18.75,
    totalValue: 382.50,
    comments: "Routine pick-up. Paving subgrade binder.",
    scaleIdInbound: "Scale-A1",
    scaleIdOutbound: "Scale-B2",
    operatorId: "OP-JohnD",
    auditHistory: [
      { timestamp: "2026-06-22 09:05 AM", action: "First Weigh Inbound", user: "OP-JohnD", details: "First weighing recorded gross weight of 38.90t" },
      { timestamp: "2026-06-22 09:21 AM", action: "Second Weigh Outbound", user: "OP-JohnD", details: "Second weighing recorded tare weight of 18.50t" }
    ],
    type: "Account",
    jobOrder: "JOB-2026-02",
    lotNo: "LOT-B-11",
    transactionCode: "TR-AC-913",
    accountBalance: 5120.00
  },
  {
    id: "TX-40914",
    ticketNo: "WB-991246",
    vehicleReg: "QD-11-AA",
    driverName: "Bradley Cooper",
    customerId: "C-404",
    customerName: "Metro Roads Joint Venture",
    productId: "P-125",
    productName: "Road Base 40mm",
    carrierName: "Star Bulk Haulage",
    grossWeight: 51.30,
    tareWeight: 19.10,
    netWeight: 32.20,
    firstWeighTime: "2026-06-22 09:44 AM",
    secondWeighTime: "2026-06-22 10:02 AM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.APPROVED,
    basePrice: 22.00,
    totalValue: 708.40,
    comments: "Government bulk supply order under Contract #MR-2024.",
    scaleIdInbound: "Scale-A1",
    scaleIdOutbound: "Scale-B1",
    operatorId: "OP-SarahK",
    auditHistory: [
      { timestamp: "2026-06-22 09:44 AM", action: "First Weigh Inbound", user: "OP-SarahK", details: "Inbound active. Standard tare auto-filled." },
      { timestamp: "2026-06-22 10:02 AM", action: "Second Weigh Outbound", user: "OP-SarahK", details: "Completed transaction." },
      { timestamp: "2026-06-22 11:30 AM", action: "Administrator Review", user: "Admin User", details: "Approved for billing queue. Credit check passed." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-01",
    lotNo: "LOT-A-42",
    transactionCode: "TR-AC-914",
    accountBalance: 3491.10
  },
  {
    id: "TX-40915",
    ticketNo: "WB-991247",
    vehicleReg: "ES-04-SS",
    driverName: "Sarah Connor",
    customerId: "C-403",
    customerName: "Pinnacle Concrete Solutions",
    productId: "P-126",
    productName: "Concrete Sand",
    carrierName: "Echo Sand Transport",
    grossWeight: 28.10,
    tareWeight: 9.80,
    netWeight: 18.30,
    firstWeighTime: "2026-06-22 10:15 AM",
    secondWeighTime: "2026-06-22 10:35 AM",
    siteName: "Bayside Coastal Sands",
    status: TransactionStatus.APPROVED,
    basePrice: 16.00,
    totalValue: 292.80,
    comments: "Fine aggregate sample. Immediate payment client.",
    scaleIdInbound: "Scale-C1",
    scaleIdOutbound: "Scale-C2",
    operatorId: "OP-SarahK",
    auditHistory: [
      { timestamp: "2026-06-22 10:15 AM", action: "First Weigh", user: "OP-SarahK", details: "Inbound scale locked" },
      { timestamp: "2026-06-22 10:35 AM", action: "Second Weigh", user: "OP-SarahK", details: "Outbound weight set" },
      { timestamp: "2026-06-22 13:02 PM", action: "Review & Pre-Authorize", user: "OP-SarahK", details: "System approved automatically." }
    ],
    type: "Cash",
    jobOrder: "JOB-2026-C3",
    lotNo: "LOT-C-05",
    transactionCode: "TR-CS-915",
    accountBalance: 0.00
  },
  {
    id: "TX-40916",
    ticketNo: "WB-991248",
    vehicleReg: "IC-88-TT",
    driverName: "Marcus Fletcher",
    customerId: "C-401",
    customerName: "Apex Infrastructure Group",
    productId: "P-136",
    productName: "Recycled Concrete",
    carrierName: "Indie Carters Network",
    grossWeight: 56.40,
    tareWeight: 24.60,
    netWeight: 31.80,
    firstWeighTime: "2026-06-22 11:10 AM",
    secondWeighTime: "2026-06-22 11:32 AM",
    siteName: "Western Eco-Recycling Depot",
    status: TransactionStatus.ON_HOLD,
    basePrice: 15.50,
    totalValue: 492.90,
    comments: "HEAVY LOAD. Carrier vehicle flagged for tire pressure warning prior to scale entry. Needs engineering inspection on tare variance.",
    scaleIdInbound: "Scale-W1",
    scaleIdOutbound: "Scale-W1",
    operatorId: "OP-SteveG",
    auditHistory: [
      { timestamp: "2026-06-22 11:10 AM", action: "First Weigh In", user: "OP-SteveG", details: "Gross weight 56.40t recorded." },
      { timestamp: "2026-06-22 11:32 AM", action: "Second Weigh Out", user: "OP-SteveG", details: "Tare 24.60t is 1.2t over registered digital tare profile of 23.4t." },
      { timestamp: "2026-06-22 11:45 AM", action: "Status Modified", user: "OP-SteveG", details: "Locked in status ON_HOLD due to tare weight variance discrepancy of >5%." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-04",
    lotNo: "LOT-D-99",
    transactionCode: "TR-AC-916",
    accountBalance: 12900.40
  },
  {
    id: "TX-40917",
    ticketNo: "WB-991249",
    vehicleReg: "IC-41-YY",
    driverName: "Nesta Harris",
    customerId: "C-405",
    customerName: "Yarra Eco-landscaping",
    productId: "P-137",
    productName: "Top Soil",
    carrierName: "Indie Carters Network",
    grossWeight: 23.60,
    tareWeight: 13.90,
    netWeight: 9.70,
    firstWeighTime: "2026-06-22 11:50 AM",
    secondWeighTime: "2026-06-22 12:08 PM",
    siteName: "Western Eco-Recycling Depot",
    status: TransactionStatus.INVOICED,
    basePrice: 14.00,
    totalValue: 135.80,
    comments: "Delivered for Carlton Park gardens. Immediate billing.",
    scaleIdInbound: "Scale-W1",
    scaleIdOutbound: "Scale-W1",
    operatorId: "OP-SteveG",
    auditHistory: [
      { timestamp: "2026-06-22 11:50 AM", action: "First Weigh", user: "OP-SteveG", details: "Inbound registered." },
      { timestamp: "2026-06-22 12:08 PM", action: "Second Weigh", user: "OP-SteveG", details: "Outbound completed. Ticket printed." },
      { timestamp: "2026-06-22 14:00 PM", action: "Billing Dispatched", user: "Admin User", details: "Invoiced generated. Invoice ID: INV-2026-00441." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-05",
    lotNo: "LOT-E-03",
    transactionCode: "TR-AC-917",
    accountBalance: 1500.00
  },
  {
    id: "TX-40918",
    ticketNo: "WB-991250",
    vehicleReg: "XY-99-ZZ",
    driverName: "James Peterson",
    customerId: "C-401",
    customerName: "Apex Infrastructure Group",
    productId: "P-129",
    productName: "Granite 10mm",
    carrierName: "Star Bulk Haulage",
    grossWeight: 44.10,
    tareWeight: 14.20,
    netWeight: 29.90,
    firstWeighTime: "2026-06-21 13:12 PM",
    secondWeighTime: "2026-06-21 13:40 PM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.INVOICED,
    basePrice: 26.00,
    totalValue: 777.40,
    comments: "Standard gravel dispatch.",
    scaleIdInbound: "Scale-A2",
    scaleIdOutbound: "Scale-B2",
    operatorId: "OP-SarahK",
    auditHistory: [
      { timestamp: "2026-06-21 13:12 PM", action: "Weighed", user: "OP-SarahK", details: "Dispatched Inbound" },
      { timestamp: "2026-06-21 13:40 PM", action: "Weighed", user: "OP-SarahK", details: "Completed Outbound" },
      { timestamp: "2026-06-22 14:00 PM", action: "Invoiced", user: "Billing-Automated", details: "Batch invoice run #B-1992" }
    ],
    type: "Account",
    jobOrder: "JOB-2026-01",
    lotNo: "LOT-A-42",
    transactionCode: "TR-AC-918",
    accountBalance: 2720.60
  },
  {
    id: "TX-40919",
    ticketNo: "WB-991251",
    vehicleReg: "QD-11-AA",
    driverName: "Bradley Cooper",
    customerId: "C-404",
    customerName: "Metro Roads Joint Venture",
    productId: "P-125",
    productName: "Road Base 40mm",
    carrierName: "Star Bulk Haulage",
    grossWeight: 52.40,
    tareWeight: 19.10,
    netWeight: 33.30,
    firstWeighTime: "2026-06-22 14:15 PM",
    secondWeighTime: "2026-06-22 14:38 PM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.PENDING,
    basePrice: 22.00,
    totalValue: 732.60,
    comments: "Road base supply. Safe loading capacity limits verified on Scale B.",
    scaleIdInbound: "Scale-A1",
    scaleIdOutbound: "Scale-B1",
    operatorId: "OP-JohnD",
    auditHistory: [
      { timestamp: "2026-06-22 14:15 PM", action: "Inbound Weigh", user: "OP-JohnD", details: "Gross weight 52.40t recorded." },
      { timestamp: "2026-06-22 14:38 PM", action: "Outbound Weigh", user: "OP-JohnD", details: "Tare weight 19.10t recorded." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-01",
    lotNo: "LOT-A-42",
    transactionCode: "TR-AC-919",
    accountBalance: 1980.20
  },
  {
    id: "TX-40920",
    ticketNo: "WB-991252",
    vehicleReg: "WB-40-EE",
    driverName: "Mustafa Al-Azawi",
    customerId: "C-402",
    customerName: "Bayside Civil Construction",
    productId: "P-124",
    productName: "Crusher Dust",
    carrierName: "RoadKings Logistics",
    grossWeight: 39.10,
    tareWeight: 18.50,
    netWeight: 20.60,
    firstWeighTime: "2026-06-22 15:02 PM",
    secondWeighTime: "2026-06-22 15:20 PM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.PENDING,
    basePrice: 18.75,
    totalValue: 386.25,
    comments: "Second split ticket for paving overlay. No safety triggers tripped.",
    scaleIdInbound: "Scale-A2",
    scaleIdOutbound: "Scale-B2",
    operatorId: "OP-JohnD",
    auditHistory: [
      { timestamp: "2026-06-22 15:02 PM", action: "Inbound Scale", user: "OP-JohnD", details: "Registered." },
      { timestamp: "2026-06-22 15:20 PM", action: "Outbound Scale", user: "OP-JohnD", details: "Finished." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-02",
    lotNo: "LOT-B-11",
    transactionCode: "TR-AC-920",
    accountBalance: 4733.75
  },
  {
    id: "TX-40921",
    ticketNo: "WB-991253",
    vehicleReg: "ES-04-SS",
    driverName: "Sarah Connor",
    customerId: "C-403",
    customerName: "Pinnacle Concrete Solutions",
    productId: "P-126",
    productName: "Concrete Sand",
    carrierName: "Echo Sand Transport",
    grossWeight: 27.90,
    tareWeight: 9.80,
    netWeight: 18.10,
    firstWeighTime: "2026-06-22 15:45 PM",
    secondWeighTime: "2026-06-22 16:04 PM",
    siteName: "Bayside Coastal Sands",
    status: TransactionStatus.PENDING,
    basePrice: 16.00,
    totalValue: 289.60,
    comments: "Final pickup load of day. Structural mixing sand.",
    scaleIdInbound: "Scale-C1",
    scaleIdOutbound: "Scale-C2",
    operatorId: "OP-SarahK",
    auditHistory: [
      { timestamp: "2026-06-22 15:45 PM", action: "First Weigh", user: "OP-SarahK", details: "Gross weight 27.90t" },
      { timestamp: "2026-06-22 16:04 PM", action: "Second Weigh", user: "OP-SarahK", details: "Tare weight 9.80t" }
    ],
    type: "Cash",
    jobOrder: "JOB-2026-C3",
    lotNo: "LOT-C-05",
    transactionCode: "TR-CS-921",
    accountBalance: 0.00
  },
  {
    id: "TX-40922",
    ticketNo: "WB-991254",
    vehicleReg: "IC-88-TT",
    driverName: "Marcus Fletcher",
    customerId: "C-406",
    customerName: "Gippsland Earth Group",
    productId: "P-138",
    productName: "Fill Material",
    carrierName: "Indie Carters Network",
    grossWeight: 54.80,
    tareWeight: 24.60,
    netWeight: 30.20,
    firstWeighTime: "2026-06-22 16:11 PM",
    secondWeighTime: "2026-06-22 16:35 PM",
    siteName: "Western Eco-Recycling Depot",
    status: TransactionStatus.ON_HOLD,
    basePrice: 12.50,
    totalValue: 377.50,
    comments: "SUSPENDED ACCOUNT TRIGGER. Customer Gippsland Earth Group account status is current tagged Suspended. Hold placed immediately on ticketing completion.",
    scaleIdInbound: "Scale-W1",
    scaleIdOutbound: "Scale-W1",
    operatorId: "OP-SteveG",
    auditHistory: [
      { timestamp: "2026-06-22 16:11 PM", action: "Automated Check", user: "Billing-Engine", details: "Detected Account status suspended. Set Lockout." },
      { timestamp: "2026-06-22 16:35 PM", action: "Hold Applied", user: "OP-SteveG", details: "Transaction completed with status set to ON_HOLD as requested by credit locking module." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-06",
    lotNo: "LOT-F-12",
    transactionCode: "TR-AC-922",
    accountBalance: -450.00
  },
  {
    id: "TX-40923",
    ticketNo: "WB-991255",
    vehicleReg: "IC-41-YY",
    driverName: "Nesta Harris",
    customerId: "C-405",
    customerName: "Yarra Eco-landscaping",
    productId: "P-137",
    productName: "Top Soil",
    carrierName: "Indie Carters Network",
    grossWeight: 24.10,
    tareWeight: 13.90,
    netWeight: 10.20,
    firstWeighTime: "2026-06-21 09:20 AM",
    secondWeighTime: "2026-06-21 09:42 AM",
    siteName: "Western Eco-Recycling Depot",
    status: TransactionStatus.APPROVED,
    basePrice: 14.00,
    totalValue: 142.80,
    comments: "Gardening load. Clean soil certified green.",
    scaleIdInbound: "Scale-W1",
    scaleIdOutbound: "Scale-W1",
    operatorId: "OP-SteveG",
    auditHistory: [
      { timestamp: "2026-06-21 09:20 AM", action: "Scale Weigh-In", user: "OP-SteveG", details: "Recorded weight 24.1t." },
      { timestamp: "2026-06-21 09:42 AM", action: "Scale Weigh-Out", user: "OP-SteveG", details: "Recorded weight 13.9t." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-05",
    lotNo: "LOT-E-03",
    transactionCode: "TR-AC-923",
    accountBalance: 1357.20
  },
  {
    id: "TX-40924",
    ticketNo: "WB-991256",
    vehicleReg: "XY-99-ZZ",
    driverName: "James Peterson",
    customerId: "C-404",
    customerName: "Metro Roads Joint Venture",
    productId: "P-123",
    productName: "Crushed Rock 20mm",
    carrierName: "Star Bulk Haulage",
    grossWeight: 44.60,
    tareWeight: 14.20,
    netWeight: 30.40,
    firstWeighTime: "2026-06-22 16:40 PM",
    secondWeighTime: "2026-06-22 16:58 PM",
    siteName: "Melbourne Eastern Quarry",
    status: TransactionStatus.PENDING,
    basePrice: 24.50,
    totalValue: 744.80,
    comments: "Crushed rock load for southern arterial highway works.",
    scaleIdInbound: "Scale-A1",
    scaleIdOutbound: "Scale-B2",
    operatorId: "OP-SarahK",
    auditHistory: [
      { timestamp: "2026-06-22 16:40 PM", action: "First Weigh", user: "OP-SarahK", details: "Logged inbound." },
      { timestamp: "2026-06-22 16:58 PM", action: "Second Weigh", user: "OP-SarahK", details: "Logged outbound. Ready for back-office audit review." }
    ],
    type: "Account",
    jobOrder: "JOB-2026-01",
    lotNo: "LOT-A-42",
    transactionCode: "TR-AC-924",
    accountBalance: 1225.30
  }
];

export const MOCK_ADMIN_USER: AdminUser = {
  id: "AD-01",
  name: "Admin User",
  role: "Administrator",
  email: "admin.user@uniweigh.com",
  lastActive: "Active Now",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=120&auto=format&fit=crop",
  sites: ["Melbourne Eastern Quarry", "Bayside Coastal Sands", "Western Eco-Recycling Depot"]
};

export interface DemoLoginAccount {
  role: string;
  name: string;
  email: string;
  password: string;
}

export const DEMO_LOGIN_ACCOUNTS: DemoLoginAccount[] = [
  {
    role: "Administrator",
    name: "Admin User",
    email: "admin.user@uniweigh.com",
    password: "admin123"
  },
  {
    role: "Developer",
    name: "Dev User",
    email: "dev.user@uniweigh.com",
    password: "developer123"
  },
  {
    role: "Weighbridge Operator",
    name: "John Davis",
    email: "john.davis@uniweigh.com",
    password: "operator123"
  },
  {
    role: "Billing Auditor",
    name: "Sarah Jenkins",
    email: "sarah.k@uniweigh.com",
    password: "auditor123"
  }
];

export function authenticateDemoUser(email: string, password: string): AdminUser | null {
  const account = DEMO_LOGIN_ACCOUNTS.find(
    (entry) => entry.email.toLowerCase() === email.trim().toLowerCase() && entry.password === password
  );
  if (!account) return null;

  const roleIds: Record<string, string> = {
    Administrator: "AD-01",
    Developer: "DV-01",
    "Weighbridge Operator": "OP-01",
    "Billing Auditor": "AU-01"
  };

  return {
    id: roleIds[account.role] ?? "AD-01",
    name: account.name,
    role: account.role,
    email: account.email,
    lastActive: "Active Now",
    avatarUrl: MOCK_ADMIN_USER.avatarUrl,
    sites: MOCK_ADMIN_USER.sites
  };
}

export const MOCK_ROLES = [
  { name: "Administrator", description: "Full system administration access, user setup, database configuration, locking override, billing triggers.", usersCount: 2 },
  { name: "Developer", description: "Full system access equivalent to Administrator, plus authority to approve new weighbridge sites for operational use.", usersCount: 1 },
  { name: "Weighbridge Operator", description: "Add transactions, weigh trucks on scale entry and exit, visual logs lookup.", usersCount: 8 },
  { name: "Billing Auditor", description: "Export CSV files, review approved tickets, transition to invoicing queues.", usersCount: 3 }
];

export const DEFAULT_DOCKET_CONFIG: DocketConfig = {
  businessName: "Growden Excavations Pty Ltd trading as Black Oak Quarries",
  poBox: "P.O. Box 44 Iron Knob SA 5611",
  contact: "0417 629 312 (After hours: 0418 843 208)",
  fax: "(08) 86462199",
  email: "french9@activ8.net.au",
  abn: "93 095 377 316",
  eftAccountName: "Black Oak Quarries",
  eftBsb: "085-960",
  eftAccountNo: "7166 28418",
  logoColor: "#10b981", // elegant emerald-500 representing the green in the logo
  themeColor: "#0f172a",
  weighbridgeLocation: "Iron Knob",
  showLogo: true,
  logoUrl: "/pdf-icon.png",
  invoiceTitle: "Commercial Tax Invoice",
  cashInvoiceNotes: "Thank you for your business. For cash/card sales, EFT payments are processed prior to vehicle dispatch.",
  accountInvoiceNotes: "Tax Invoice raised directly against approved credit ledger. Contract Terms apply. Do not pay this document.",
};

